sudo : required
dist : trusty
cache : 
    - apt
branches : 
    only : 
        - master
        - dev
before_install :
    - sudo apt-get update -qq
script :
    - bash -eu ./docker_install.sh
    - docker -v

