sudo : required
dist : trusty
cache : 
  - apt
branches : 
  only : 
    - master
    - dev
before_install :
  - sudo apt-get update -qq
script :
  - curl -SsfL https://git.io/ubuntu-docker-install | bash
  - docker -v
  - curl -SsfL https://git.io/ubuntu-docker-compose-install | bash

